### ISSUE TITLE
Blog design transparency

### ISSUE THREAD

**Issue by MariaLiquid** [liqd/liqd-site#11]
**URL:** https://liqd.net/de/blog/
**user:** any
**expected behaviour:** line in Preview-Teasers should still be readable in the Blog article overview
**behaviour:** transparency creates an odd diagonal line that makes part of the text unreadable
**important screensize:** Desktop
**device & browser:** Firefox MacBook Air 2020
**Comment/Question:** Can we change the preview teasers so that it's all the same transparency and parts of it isn't cut off? 

**Note:** This is not an issue concerning the django update but rather a small design issue that doesn't have a high priority atm and that can be fixed in a later sprint. 

<img width="968" alt="Bildschirmfoto 2022-04-28 um 16 59 32" src="https://user-images.githubusercontent.com/103425440/165783229-8989c98e-b90d-4a8a-b802-b5e794069172.png">

**Comment by phillimorland** [comment]
@MariaLiquid how many lines do you want to be visible? I think the original design is intended for them to disapear in the fade and I wouldn't change the design unless @mcastro-lqd has an alternate suggestion, but I can alter how many lines are shown before the fade, would that work?

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd or @maxliqd  Should we change it or keep it like it is?

**Comment by maxliqd** [comment]
@phillimorland @mcastro-lqd: I would say three lines visible. This way we would be safe you can read the headline und the first sentence of the blog post.

**Comment by maxliqd** [comment]
@phillimorland @mcastro-lqd Sorry, that was too quick. If we go for three lines, we would loose the fade out in most teasers on the blog page. So two lines visible would be better.
