### ISSUE TITLE
6062 Image sizes single teaser

### ISSUE THREAD

**Issue by maxliqd** [liqd/liqd-site#112]
**URL:** https://dev.liqd.net/de/academy-landing-page-test/
**user:** CMS editor
**expected behaviour:** Teaser images are always the same size, regardless of size of used image
**behaviour:** Teaser image sizes vary
**important screensize:** desktop
**device & browser:** 
**Comment/Question:** 
On the GDB website this is implemented. That's where the expectation is coming from, if you were wondering.
Related issue: https://github.com/liqd/liqd-site/issues/111

Screenshot?
![image](https://user-images.githubusercontent.com/94360651/187482535-b9a42674-d045-4546-8971-a9e6adec2567.png)

<img width="996" alt="image" src="https://user-images.githubusercontent.com/94360651/187402911-2b2db459-341d-4a0b-b76a-7ffb4636c19c.png">

<img width="419" alt="image" src="https://user-images.githubusercontent.com/94360651/187402716-248f6d34-6e87-4f77-bf6b-d471f2e59340.png">
<img width="391" alt="image" src="https://user-images.githubusercontent.com/94360651/187402830-e605969f-9f67-4319-944c-8286150c8528.png">

**Comment by phillimorland** [comment]
@maxliqd I think this is fixed with the other issue but you added a screen shot of the single teaser there, what's wrong with that one?

**Comment by phillimorland** [comment]
@maxliqd cool thanks for clarification!
