### ISSUE TITLE
move TranslatedStructValue to translations.py

### ISSUE THREAD

**Issue by Rineee** [liqd/liqd-site#140]
**URL:** 
**user:** 
**expected behaviour:** all translated fields are in one place
**behaviour:** TranslatedStructValue is currently in core/models/snippets.py, where it is used
**important screensize:**
**device & browser:** 
**Comment/Question:** also make it behave like TranslatedField, see discussion [here](https://github.com/liqd/liqd-site/pull/130/files/7eeccc412dc13ddb0fb6bc7155f23460f2030e22..73e90032bbbc16ffd28fe496707120a805a33bcb#r964442783)

Screenshot?

**Comment by hello-kathi** [comment]
@Rineee should that be done before release on Stage/Prod?

**Comment by Rineee** [comment]
@hello-kathi No, that is not urgent, no need to do that before release.
