### ISSUE TITLE
#6064 [liqd.net] second-level navigation

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/liqd-site#145]
**URL:** https://dev.liqd.net/en/academy-landing-page/
**user:** *all*
**important screensize:** *Desktop*
**device & browser:** *Safari Version 15.6.1 (17613.3.9.1.16) and Chrome Version 104.0.5112.101 (Official Build) (x86_64)*
**Comment/Question:** *Shall we use the white gradient behind the menu here as well?*

<img width="1037" alt="Screenshot 2022-09-08 at 11 39 27" src="https://user-images.githubusercontent.com/59610786/189089895-d379b0e7-51bc-4b6b-8600-ebb50d8da453.png">
<img width="767" alt="Screenshot 2022-09-08 at 11 40 50" src="https://user-images.githubusercontent.com/59610786/189089937-b1983ff0-784c-4302-9c61-740437861ead.png">

**Comment by phillimorland** [comment]
Note: I thought the nav text should turn white on dark backgrounds?! but can add fade out instead

**Comment by hello-kathi** [comment]
@mcastro-lqd what do you think? I think fade out is fine, because it is, even in white, not that readable.

**Comment by khamui** [comment]
not sure if I am testing this correctly or this issue has been solved in the meantime?
Second level nav is in front of the white part for me. Could you please confirm @mcastro-lqd or @hello-kathi ?

<img width="1952" alt="Bildschirm­foto 2023-02-20 um 15 33 05" src="https://user-images.githubusercontent.com/52801593/220135017-15f98f73-b1d9-49e3-8cc6-418b8bc71007.png">

**Comment by philli-m** [comment]
@khamui when you scroll the background colour should fade in, not be solid and make nav items less visible. the issue is still present

**Comment by khamui** [comment]
@philli-m thanks, will have another look then
