### ISSUE TITLE
6060 intro text LA landing page box too big on large desktop screens

### ISSUE THREAD

**Issue by maxliqd** [liqd/liqd-site#147]
**URL:** https://dev.liqd.net/de/academy-landing-page-test/
**user:** visitor
**expected behaviour:** less space around intro text/ smaller box with gradient background
**behaviour:** gradient background of intro text covers half of the page
**important screensize:**desktop, 1920px and more
**device & browser:** chrome, max
**Comment/Question:** 
@mcastro-lqd Is this the intended design?
Screenshot?
![image](https://user-images.githubusercontent.com/94360651/189349869-a8360ba7-70c6-4a7d-b071-154321cb4ac1.png)

**Comment by mcastro-lqd** [comment]
@maxliqd @phillimorland The design is a bit different, but I thought there should be a technical reason for that. I would also recommend that the text here shouldn't be so long, it should be max 3 lines around ~105 characters 

<img width="1458" alt="Screenshot 2022-09-14 at 14 54 57" src="https://user-images.githubusercontent.com/59610786/190159975-15bda853-e2bb-4570-8bb6-e294bf23a9a4.png">

<img width="1726" alt="Screenshot 2022-09-14 at 14 55 15" src="https://user-images.githubusercontent.com/59610786/190159930-ff26bc38-86fc-4cc7-b9e8-8372bed9feb8.png">

**Comment by phillimorland** [comment]
@maxliqd @mcastro-lqd no, not intentional, the vertical padding issue is just a leaked style from another header. The horizontal we do not set however as we use columns to dictate the width of the text and the width of the container with the background is a general setting for the whole site, is that ok to leave like that?
