### ISSUE TITLE
Dropdown Liqd Mobile 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/liqd-site#15]
URL: https://liqd.net/en/academy/
user: any
behaviour: I don't know why but currently the content texts are blue on my Mobile. 
device & browser: mobile Safari

![IMG_2663](https://user-images.githubusercontent.com/59610786/169093206-2ccb787a-a9cb-49b4-8f87-347474c4f1fb.jpg)

**Comment by phillimorland** [comment]
no need to wait, it's easy fix

**Comment by phillimorland** [comment]
@mcastro-lqd can you re-test this on dev? I don't have a test device at home but I think it should be fine although safari is apparently known to do this so not sure

**Comment by mcastro-lqd** [comment]
@phillimorland Yeah, but it happens when I use Chrome too :(
![IMG_6102](https://user-images.githubusercontent.com/59610786/187886895-b59c0837-a1a0-4727-8a82-8caa33942474.PNG)
![IMG_6103](https://user-images.githubusercontent.com/59610786/187887221-f728a770-c852-4a81-8bdd-0db90d1769fb.PNG)
