### ISSUE TITLE
Category Filtering Block 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/liqd-site#16]
URL: https://liqd.net/en/academy/ 
user: any
important screensize: Desktop
device & browser: Desktop Safari
Comment: Would it be possible to deactivate the filter once clicked again on them? 
Ex: User clicks on Digital Civic Society and then they want to undo. User clicks again and filter is deactivated. 

<img width="887" alt="Screenshot 2022-05-18 at 18 24 28" src="https://user-images.githubusercontent.com/59610786/169093445-06fe424b-ac11-4f35-80b8-d719b4ceea06.png">

**Comment by phillimorland** [comment]
duplicate https://github.com/liqd/liqd-site/issues/9
