### ISSUE TITLE
Dividers are gone

### ISSUE THREAD

**Issue by MariaLiquid** [liqd/liqd-site#165]
**URL:** https://liqd.net/de/academy/moderation/
**user:** *moderator/ initiator/ participants/ visitors (non-logged-in)/ admin/ cms-editors/ developers*
**expected behaviour:** *there used to be text dividers that you could add in the text menu on wagtail. Should look sth like this (bottom of the text): https://liqd.net/de/academy/erste-schritte-zur-digitalen-barrierefreiheit/ *
**behaviour:** *Can't add Dividers to Articles anymore*
**important screensize:** *mobile? desktop?*
**device & browser:** *e.g. Desktop, firefox 68.0.2 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?* 

<img width="756" alt="Bildschirmfoto 2022-09-29 um 14 55 48" src="https://user-images.githubusercontent.com/103425440/193024931-b33cedd9-36a2-4d27-96a3-42f30c875940.png">

**Comment by phillimorland** [comment]
@MariaLiquid we came across same issue in another project and found a work around for now which is using `---` which will become a line, not sure if you already knew that but just in case :)

**Comment by MariaLiquid** [comment]
ah super nice, thanks @phillimorland!! Will try that next time

**Comment by philli-m** [comment]
NOTE: should be fixed with wagtail update
