### ISSUE TITLE
#6812 [liqd.net] video + audio embed

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/liqd-site#238]
**URL:** https://dev.liqd.net/admin/pages/341/edit/#tab-german
**user:** *admin/ cms-editors*
**expected behaviour:** *I expect to upload videos and be able to see them*
**behaviour:** *Currently the video apparently gets uploaded in documents but it doesn't work on preview*
**important screensize:** *Both*
**device & browser:** *Safari Version 16.1 (18614.2.9.1.12)*
<img width="1326" alt="Screenshot 2023-01-17 at 10 37 43" src="https://user-images.githubusercontent.com/59610786/212864003-f956b43f-c4b0-409e-97f4-02b51207c939.png">

**Comment by phillimorland** [comment]
@mcastro-lqd can't reproduce, in preview sidebar I see the video, can you try with firefox or chrome?

**Comment by mcastro-lqd** [comment]
@phillimorland It worked on Chrome

**Comment by mcastro-lqd** [comment]
@phillimorland Sorry, actually it was my fault since the video I uploaded was mov and I didn't wait enough for the Liqd tank one

**Comment by phillimorland** [comment]
awesome will close then :)
