### ISSUE TITLE
Videoblock is not available on Text pages

### ISSUE THREAD

**Issue by hello-kathi** [liqd/liqd-site#240]
**URL:** https://dev.liqd.net/de/videoblocktextpage/
**user:** Admin
**expected behaviour:** If I create a Text Page I can put in a Video/audio
**behaviour:** I can't
**important screensize:**
**device & browser:** firefox, safari, google
**Comment/Question:** 

Screenshot?

**Comment by khamui** [comment]
@hello-kathi after checking in code, there is a page-type which allows you to add video blocks (any blocks) to the page. It is called: `Default Page with several Blocks`. This can be closed then?

**Comment by philli-m** [comment]
just to add to this, the text page is for imprint ect. and it uses a single rich text block and no other content type is added to it, (links are considered richtext). Is there any purpose to adding a video block to a purely text page?

**Comment by hello-kathi** [comment]
@khamui @philli-m thats true. I was just thinking, because it used for more then the impressum. But yes, you are right. Sorry, I will close it.
