### ISSUE TITLE
Academy: Teaser Text is not shown

### ISSUE THREAD

**Issue by hello-kathi** [liqd/liqd-site#303]
**URL:** https://liqd.net/admin/pages/353/edit/#tab-german
**user:** 
**expected behaviour:** If I write something in the teaser block, it will be shown on the page (after saving and publishing of course)
**behaviour:** It is not shown, no matter if saved or published.
**important screensize:** 
**device & browser:** firefox, safari, chrome
**Comment/Question:** 

Screenshot?

**Comment by MariaLiquid** [comment]
this is still an issue, however, only for academy. On the blog, the teaser is shown on this page (https://liqd.net/de/blog/), just not in the article. If the teasers could be visible for academy (in the text), that'd be great! For the blog, it doesn't need to be changed.
