### ISSUE TITLE
Duplicated text in academy/open-source-und-free-software-im-vergleich

### ISSUE THREAD

**Issue by Sjlver** [liqd/liqd-site#368]
**URL:** https://liqd.net/en/academy/open-source-und-free-software-im-vergleich/
**behaviour:** Search for the text below; it is repeated twice on the site, with the second occurrence right after the first.
**expected behaviour:** The paragraph should only appear once.

> Ein weiterer wichtiger Unterschied besteht darin, dass Free Software in der Regel von einer ethischen und politischen Perspektive betrachtet wird, während Open Source in erster Linie auf technischen und wirtschaftlichen Aspekten basiert. Beide Konzepte haben dazu beigetragen, die Softwareindustrie zu verändern und den Zugang zu Technologie für mehr Menschen zu ermöglichen.

**Comment by goapunk** [comment]
thanks for the hint @Sjlver :) @MariaLiquid @hello-kathi tagging you as probably something for you

**Comment by MariaLiquid** [comment]
@Sjlver thank you for pointing that out! 💪 We have changed it a while ago, sorry for my late reply on here!
