### ISSUE TITLE
Delete Date for Academy Articles 

### ISSUE THREAD

**Issue by MariaLiquid** [liqd/liqd-site#374]
**URL:** https://liqd.net/de/academy/
**user:** any
**expected behaviour:** Can we remove the mandatory dates for academy articles? Wagtail asks us to put something down put would prefer if the articles didn't have dates
**behaviour:** 
**important screensize:** all
**device & browser:** all
**Comment/Question:** 
Screenshot?
<img width="1375" alt="Bildschirmfoto 2024-06-13 um 10 54 38" src="https://github.com/liqd/liqd-site/assets/103425440/fee90605-59ce-4ce7-8085-75bc0c984284">

**Comment by goapunk** [comment]
@MariaLiquid I think this will need some more thoughts. Currently the pages are sorted by date, but what happens to articles without date? Do they always appear on the first page? Or on the last? Or do we remove the sorting by date and only keep the alphabetical one?

**Comment by MariaLiquid** [comment]
@goapunk, good question, sorry should have elaborated! I actually thought we could keep the dates (behind the scenes), but just not make them visible on the overview? That way, the order of content can stay the same, but it just looks a little less "Blog-y". The date could even remain visible, but maybe we could rather just show it on the bottom of each article, not in the overview. what do you think?

**Comment by goapunk** [comment]
Ah, yes we can of course just hide the dates from the list, that makes it much easier.
