### ISSUE TITLE
#3025 dropdown issues

### ISSUE THREAD

**Issue by rittermo** [liqd/liqd-site#8]
I cannot close the dropdown for the filters as the arrow is gone. Also, the dropdown opens in a vertically centered way and pushes away the content underneath it. This is a bit disorienting and it would be better if the dropdown could be an overlay over the content
Safari 13.1
https://stage.liqd.net/de/liquid-academy/

<img width="1045" alt="Bildschirmfoto 2020-06-25 um 16 27 56" src="https://user-images.githubusercontent.com/15341015/85740315-d08d6880-b701-11ea-8f35-1e09bfb111e7.png">

**Comment by MariaLiquid** [comment]
@rittermo should we leave this issue open? I actually prefer the dropdown not overlaying the content, but rather pushing it down (personal preference). However, would be great to be able to close the filters, I agree. Wdyt?

**Comment by rittermo** [comment]
@MariaLiquid We can close the issue
