### ISSUE TITLE
Content question about image

### ISSUE THREAD

**Issue by phillimorland** [liqd/liqd-site#84]
checking the site on a wide screen monitor it looks like below, should the image ratio for project images be enforced as it looks a bit messy or is that just me? maybe question for @mcastro-lqd @maxliqd @lthueer ?
https://liqd.net/en/projects/

![screenshot(33)](https://user-images.githubusercontent.com/5871230/186608660-19cc607c-44d0-4620-8554-d698821cb918.png)

**Comment by mcastro-lqd** [comment]
Yes, I think its a good idea, but Im just afraid that the pics will be cropped wrong and some important parts will be missing, but Im happy to fix them if we can replace them

**Comment by phillimorland** [comment]
@mcastro-lqd maybe if we just have a minimum width to make it a bit easier to find shots, as content is max 1920, i guess a min width for the images of around 970 would work so they are always touching?

**Comment by maxliqd** [comment]
I am fine with whatever Marcelo says.
