### ISSUE TITLE
[liqd.net] #6360 Background Intro Text

### ISSUE THREAD

**Issue by maxliqd** [liqd/liqd-site#89]
**URL:** https://dev.liqd.net/de/academy-landing-page-test/
**user:** CMS editor
**expected behaviour:** 
1. Gradient colour of flubber
(nice to have 2. Settable colour)
**behaviour:** gradient, but not CI colour
**important screensize:** desktop
**device & browser:** mac, chrom
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/94360651/186702328-9d92a196-c570-4174-99df-12faa696d03f.png)

**Comment by Rineee** [comment]
@maxliqd The colour indeed is settable in the common tab of the landing page. Does that work for you?

**Comment by Rineee** [comment]
> @maxliqd The colour indeed is settable in the common tab of the landing page. Does that work for you?

I just saw that the right colors of the gradient are actuylly specified in the designs.. so you would probably like them to be the default values, right? :grin:

**Comment by maxliqd** [comment]
@Rineee If you can set them easily, why not. Thank you! And sorry, I must have missed it on the common tab, strange! But it looks great now: https://dev.liqd.net/de/academy-landing-page-test/
