### ISSUE TITLE
[liqd.net] 6090 CTA block links not obligatory

### ISSUE THREAD

**Issue by maxliqd** [liqd/liqd-site#90]
**URL:** https://dev.liqd.net/de/academy-landing-page-test/
**user:** CMS editor
**expected behaviour:** I don't accidentally forget to set a link, it is obligatory to either set internal or set external link
**behaviour:** I can leave out the link, there is a teaser without link
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Not sure: is this rather an enhancement? We did not specify it like that in the AC

Screenshot?

![image](https://user-images.githubusercontent.com/94360651/186710684-1df65e21-4b65-4584-be26-d2e7f626b86f.png)

**Comment by Rineee** [comment]
@maxliqd The problem is, that here both external and internal links should be possible and for both, we can either make them required or not, but we cannot make one required depending on if the other one was set. Does that make sense?

**Comment by maxliqd** [comment]
@Rineee okidoki
