### ISSUE TITLE
[liqd.net] Spacing beetween teaser blocks 

### ISSUE THREAD

**Issue by maxliqd** [liqd/liqd-site#91]
**URL:** https://dev.liqd.net/de/academy-landing-page-test/
**user:** visitor
**expected behaviour:** Blocks have enough space around them
**behaviour:** Little space between link single teaser and CTA black
**important screensize:**desktop and mobile
**device & browser:** 
**Comment/Question:** 
@mcastro-lqd Can you maybe take a look as well and specify?

Screenshot?

![image](https://user-images.githubusercontent.com/94360651/186710771-51d95f2c-42b3-4bf9-9d17-eda0c0f8034a.png)

**Comment by fuzzylogic2000** [comment]
Ah, no, sorry, the single teaser is not yet styled, so does not have any padding yet! I will close this and we hopefully have the block styled very soon!
