### ISSUE TITLE
6090 CTA block external link not working

### ISSUE THREAD

**Issue by maxliqd** [liqd/liqd-site#95]
**URL:** https://dev.liqd.net/de/academy-landing-page-test/
**user:** 
**expected behaviour:** external link works
**behaviour:** CMS editor can set a link, but when you click on it, the page just reloads
**important screensize:** desktop
**device & browser:** mac, chrome
**Comment/Question:** 

Screenshot?

**Comment by Rineee** [comment]
@maxliqd There was no link set, thats why it did not work. Maybe you forgot to save? You can choose the link in common panel. I now set it to link to the homepage and it works.

But it can only link to internal pages as specified in the story.

**Comment by Rineee** [comment]
Oh no sorry, I was looking at the intro.. sorry about it, I will check cta block now!
